//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentalApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int Id { get; set; }
        public Nullable<int> UserAppId { get; set; }
        public Nullable<int> CarRentalRecord { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual CarRentalRecord CarRentalRecord1 { get; set; }
        public virtual userApp userApp { get; set; }
    }
}
